### **MACS 30112 Final Project**

### **Tiger Parenting**

#### **This ipython file helps you to extract/scrape US Census American Census Survey (ACS) data**

#### **Part 1 - Load Census Wrapper**

In [7]:
# load census wrapper to get data from census through API
from census import Census
from us import states

#### **Part 2 - Import required librarries**

In [6]:
# import libraries
import pandas as pd
import numpy as np

# import libraries for visualization
import matplotlib
import seaborn

#### **Part 3 - Define US Census API Key**

In [9]:
# Insert your US Census API key
c = Census("YOUR US CENSUS API KEY GOES HERE")

#### **Part 4 - Define your variable to extarct**

- API key: https://www.census.gov/data/developers/data-sets.html
- Extract data using API examples: https://api.census.gov/data/2022/acs/acs5/examples.html
- variables lookup: https://api.census.gov/data/2022/acs/acs5/variables.html

In [22]:
#define the variables to be used in the API call

variables = [
    'NAME',     # Name of the area
    'B19013_001E',  # Median Household Income
    'B19013A_001E',  # Median Household Income (White Alone)
    'B19013B_001E'  # Median Household Income (Black or African American Alone)
     ] # Asian alone population

In [19]:
# define years from 2003 t0 2021 to extract data from the API
years = list(range(2009, 2022))

#### **Part 5 - Extract Data**

In [26]:
#loop over years and get data for each year and concatenate the data into a single dataframe
df = pd.DataFrame()
for year in years:
    print(year)
    data = c.acs.state(('NAME',) + tuple(variables), Census.ALL, year=year)
    df = pd.concat([df, pd.DataFrame(data)])

2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021

In [27]:
# dataframe and its shape
df

             NAME  B19013_001E  B19013A_001E  B19013B_001E state
0         Alabama      41216.0       47546.0       26734.0    01
1          Alaska      64635.0       70778.0       53512.0    02
2         Arizona      50296.0       52263.0       40240.0    04
3        Arkansas      38542.0       41883.0       24420.0    05
4      California      60392.0       63751.0       43397.0    06
..            ...          ...           ...           ...   ...
47     Washington      82400.0       83742.0       59874.0    53
48  West Virginia      50884.0       51585.0       34163.0    54
49      Wisconsin      67080.0       70167.0       34998.0    55
50        Wyoming      68002.0       68965.0       43621.0    56
51    Puerto Rico      21967.0       22699.0       21277.0    72

[676 rows x 5 columns]

In [32]:
# average median household income for all states
avg_df = pd.DataFrame()
avg_df['Avg medium income'] = df.groupby('NAME')['B19013_001E'].mean()
avg_df['Avg medium income white'] = df.groupby('NAME')['B19013A_001E'].mean()
avg_df['Avg medium income black'] = df.groupby('NAME')['B19013B_001E'].mean()

In [33]:
# dataframe and its shape
avg_df

,Avg medium income,Avg medium income white,Avg medium income black
NAME,,,
Alabama,45923.692308,52714.230769,30595.769231
Alaska,72937.000000,79990.230769,57644.230769
Arizona,53781.461538,55778.384615,42979.615385
Arkansas,43304.769231,46789.000000,28438.000000
California,66837.846154,70020.615385,47127.076923
Colorado,63973.230769,66393.230769,44899.615385
Connecticut,72879.000000,79056.384615,45642.230769
Delaware,62697.846154,67098.384615,47183.538462
District of Columbia,73158.230769,119188.615385,42085.230769
Florida,50777.846154,53625.153846,37474.461538
Georgia,53149.307692,60714.307692,39758.230769
Hawaii,72941.846154,72698.076923,64059.384615
Idaho,50732.307692,51435.692308,38128.461538
Illinois,60523.076923,65688.461538,36251.384615
Indiana,51660.846154,54354.076923,32309.076923
Iowa,54904.153846,56127.769231,29278.769231
Kansas,54367.153846,56330.769231,34630.846154
Kentucky,45828.307692,47400.615385,31783.230769
Louisiana,46417.461538,56328.307692,28875.615385
Maine,52003.307692,52530.076923,31973.000000
Maryland,77532.923077,86042.538462,61555.615385
Massachusetts,72464.923077,76712.076923,46402.538462
Michigan,52256.538462,55844.769231,32304.230769
Minnesota,64133.000000,66686.692308,32836.923077
Mississippi,41326.461538,51376.153846,27625.230769
Missouri,50662.153846,53541.384615,33760.692308
Montana,49362.692308,50677.615385,36573.384615
Nebraska,55211.923077,57182.076923,31182.307692
Nevada,56309.153846,59268.230769,40153.846154
New Hampshire,69659.000000,69967.769231,51334.538462
New Jersey,75725.076923,81581.769231,49540.076923
New Mexico,46646.538462,49515.923077,40168.076923
New York,61924.461538,69170.076923,44195.230769
North Carolina,49694.153846,55360.923077,35124.384615
North Dakota,57053.076923,59355.076923,31325.538462
Ohio,51667.307692,55369.230769,30310.769231
Oklahoma,48108.846154,51301.384615,31964.846154
Oregon,55194.076923,56019.307692,35935.769231
Pennsylvania,55966.461538,59244.923077,34857.461538
Puerto Rico,19832.769231,20469.153846,19232.076923
Rhode Island,60528.538462,64701.615385,39402.692308
South Carolina,48077.461538,55660.153846,31760.461538
South Dakota,52606.307692,55044.384615,35287.230769
Tennessee,47803.615385,50967.461538,34538.230769
Texas,55567.692308,59086.846154,41278.230769
Utah,63729.307692,65337.846154,40297.000000
Vermont,57055.153846,57483.615385,44000.384615
Virginia,67699.076923,72912.615385,46647.461538
Washington,65003.461538,66470.615385,46011.076923
West Virginia,42870.307692,43377.384615,29721.384615
Wisconsin,56105.692308,58552.846154,29089.307692
Wyoming,59457.461538,60508.846154,40386.461538

#### **Part 6 - Save the dataframe**

In [36]:
# save the dataframe to a csv file for future use
avg_df.to_csv('avg_median_income.csv')